# Generated by Django 5.0 on 2026-01-23 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='ville',
            field=models.CharField(default='Kinshasa', max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='commune',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='quartier',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
