# Generated by Django 5.0 on 2026-01-26 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0002_listing_ville_alter_listing_commune_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='account_type',
            field=models.CharField(choices=[('BASIC', 'Compte Gratuit'), ('PRO', 'Professionnel / Fournisseur'), ('OFFICIAL', 'Marque Officielle')], default='BASIC', max_length=15),
        ),
    ]
