# Generated by Django 5.0 on 2026-01-26 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0003_listing_slug_alter_userprofile_account_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verificationrequest',
            name='doc_front',
        ),
        migrations.AddField(
            model_name='verificationrequest',
            name='document_back',
            field=models.ImageField(blank=True, null=True, upload_to='kyc/back/%Y/'),
        ),
        migrations.AddField(
            model_name='verificationrequest',
            name='document_front',
            field=models.ImageField(default='', upload_to='kyc/front/%Y/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='verificationrequest',
            name='document_type',
            field=models.CharField(choices=[('ID_CARD', 'Carte d’identité / Électeur'), ('PASSPORT', 'Passeport'), ('RCCM', 'Registre de Commerce (Pro)')], default='ID_CARD', max_length=20),
        ),
        migrations.AddField(
            model_name='verificationrequest',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='verificationrequest',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='verificationrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('APPROVED', 'Approuvé'), ('REJECTED', 'Rejeté')], default='PENDING', max_length=15),
        ),
    ]
