# Generated by Django 5.0 on 2026-05-29 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='analyticsevent',
            new_name='analytics_a_event_t_002468_idx',
            old_name='analytics_a_event_t_7d1a4f_idx',
        ),
        migrations.RenameIndex(
            model_name='analyticsevent',
            new_name='analytics_a_busines_9b8108_idx',
            old_name='analytics_a_busines_f9e5ff_idx',
        ),
        migrations.RenameIndex(
            model_name='analyticsevent',
            new_name='analytics_a_listing_64d140_idx',
            old_name='analytics_a_listing_8a6da6_idx',
        ),
    ]
