# Generated by Django 5.0 on 2026-05-29 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_rename_analytics_a_event_t_7d1a4f_idx_analytics_a_event_t_002468_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyticsevent',
            name='event_type',
            field=models.CharField(choices=[('whatsapp_click', 'WhatsApp click'), ('listing_view', 'Listing view'), ('business_view', 'Business view'), ('share_click', 'Share click')], max_length=40),
        ),
    ]
