# Generated by Django 5.0 on 2026-08-12 11:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('catalog', '0006_productmedia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='price')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='currency')),
                ('condition', models.CharField(choices=[('NEW', 'Neuf'), ('USED', 'Occasion'), ('REFURBISHED', 'Reconditionné')], default='NEW', max_length=20, verbose_name='condition')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='stock')),
                ('location', models.CharField(blank=True, max_length=150, verbose_name='location')),
                ('is_negotiable', models.BooleanField(default=False, verbose_name='negotiable')),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('PENDING', 'En attente de validation'), ('PUBLISHED', 'Publié'), ('PAUSED', 'En pause'), ('SOLD_OUT', 'Épuisé'), ('ARCHIVED', 'Archivé')], db_index=True, default='DRAFT', max_length=20, verbose_name='status')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='published at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='accounts.sellerprofile', verbose_name='seller')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='accounts.store', verbose_name='store')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='catalog.productvariant', verbose_name='product variant')),
            ],
            options={
                'verbose_name': 'listing',
                'verbose_name_plural': 'listings',
                'db_table': 'marketplace_listings',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['seller', 'status'], name='marketplace_seller__b94bcd_idx'), models.Index(fields=['store', 'status'], name='marketplace_store_i_994535_idx'), models.Index(fields=['variant', 'status'], name='marketplace_variant_9d72aa_idx'), models.Index(fields=['status', 'created_at'], name='marketplace_status_4e6ee0_idx'), models.Index(fields=['price', 'status'], name='marketplace_price_516f6e_idx'), models.Index(fields=['condition', 'status'], name='marketplace_conditi_1a4a22_idx')],
            },
        ),
    ]
