# Generated by Django 5.0 on 2026-08-11 13:14

import accounts.models.managers
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, error_messages={'unique': 'Un utilisateur avec cet email existe déjà.'}, max_length=254, unique=True, verbose_name='email address')),
                ('phone_number', models.CharField(blank=True, db_index=True, help_text='Format international, ex: +243...', max_length=30, verbose_name='phone number')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_active', models.BooleanField(default=True, help_text="Désactive l'utilisateur au lieu de le supprimer. Les objets liés restent intacts.", verbose_name='active')),
                ('is_staff', models.BooleanField(default=False, help_text="Accès à l'admin Django.", verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'db_table': 'accounts_user',
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', accounts.models.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='accounts/avatars/%Y/%m/', verbose_name='avatar')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='bio')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='city')),
                ('country', models.CharField(blank=True, help_text='Code ISO 3166-1 alpha-2, ex: CD, FR, US', max_length=2, verbose_name='country')),
                ('preferred_currency', models.CharField(default='USD', help_text='Code ISO 4217, ex: USD, CDF, EUR', max_length=3, verbose_name='preferred currency')),
                ('language', models.CharField(default='fr', help_text='Code IETF BCP 47, ex: fr, en, sw', max_length=10, verbose_name='language')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'profile',
                'verbose_name_plural': 'profiles',
                'db_table': 'accounts_profile',
            },
        ),
        migrations.CreateModel(
            name='SellerProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('seller_type', models.CharField(choices=[('INDIVIDUAL', 'Particulier'), ('BUSINESS', 'Entreprise'), ('PROFESSIONAL', 'Professionnel')], db_index=True, default='INDIVIDUAL', max_length=20, verbose_name='seller type')),
                ('verification_status', models.CharField(choices=[('PENDING', 'En attente'), ('IN_REVIEW', 'En cours de vérification'), ('VERIFIED', 'Vérifié'), ('REJECTED', 'Rejeté'), ('SUSPENDED', 'Suspendu')], db_index=True, default='PENDING', max_length=20, verbose_name='verification status')),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, help_text='Note moyenne calculée à partir des avis clients.', max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='rating')),
                ('total_sales', models.PositiveIntegerField(default=0, help_text='Nombre total de commandes finalisées.', verbose_name='total sales')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller_profile', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'seller profile',
                'verbose_name_plural': 'seller profiles',
                'db_table': 'accounts_seller_profile',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=150, verbose_name='store name')),
                ('slug', models.SlugField(help_text='Identifiant URL unique, généré automatiquement.', max_length=150, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, max_length=2000, verbose_name='description')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='stores/logos/%Y/%m/', verbose_name='logo')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='stores/banners/%Y/%m/', verbose_name='banner')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='contact phone')),
                ('city', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='city')),
                ('address', models.TextField(blank=True, max_length=500, verbose_name='address')),
                ('is_active', models.BooleanField(default=True, help_text='Désactive la boutique sans supprimer les données. Les listings deviennent invisibles.', verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('seller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='store', to='accounts.sellerprofile', verbose_name='seller')),
            ],
            options={
                'verbose_name': 'store',
                'verbose_name_plural': 'stores',
                'db_table': 'accounts_store',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email', 'is_active'], name='accounts_us_email_f69303_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['phone_number', 'is_active'], name='accounts_us_phone_n_45a1ce_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['date_joined'], name='accounts_us_date_jo_ff39bb_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['country', 'city'], name='accounts_pr_country_4e2643_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['language'], name='accounts_pr_languag_36079a_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerprofile',
            index=models.Index(fields=['seller_type', 'verification_status'], name='accounts_se_seller__bc3cd9_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerprofile',
            index=models.Index(fields=['rating'], name='accounts_se_rating_ddf22b_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerprofile',
            index=models.Index(fields=['total_sales'], name='accounts_se_total_s_4fa70f_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerprofile',
            index=models.Index(fields=['created_at'], name='accounts_se_created_bc8155_idx'),
        ),
        migrations.AddConstraint(
            model_name='sellerprofile',
            constraint=models.CheckConstraint(check=models.Q(('rating__gte', 0.0), ('rating__lte', 5.0)), name='seller_rating_range', violation_error_message='La note doit être entre 0.00 et 5.00.'),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['slug', 'is_active'], name='accounts_st_slug_fa7c05_idx'),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['city', 'is_active'], name='accounts_st_city_d7d843_idx'),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['name', 'is_active'], name='accounts_st_name_c4827a_idx'),
        ),
    ]
