LISTING_TYPE_PRODUCT = "PRODUCT"
LISTING_TYPE_SERVICE = "SERVICE"
LISTING_TYPE_REAL_ESTATE = "REAL_ESTATE"
LISTING_TYPE_BARTER = "BARTER"
LISTING_TYPE_OTHER = "OTHER"

LISTING_TYPE_CHOICES = [
    (LISTING_TYPE_PRODUCT, "Produit"),
    (LISTING_TYPE_SERVICE, "Service"),
    (LISTING_TYPE_REAL_ESTATE, "Immobilier"),
    (LISTING_TYPE_BARTER, "Troc"),
    (LISTING_TYPE_OTHER, "Autre"),
]

PRICE_OPTIONAL_TYPES = {
    LISTING_TYPE_SERVICE,
    LISTING_TYPE_OTHER,
}

