# Generated by Django 5.0 on 2026-01-09 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_api', '0004_business_updated_at_otpcode_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otpcode',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AddField(
            model_name='business',
            name='location',
            field=models.CharField(default='Kinshasa, RDC', max_length=100),
        ),
    ]
