# Generated by Django 5.0 on 2026-01-23 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_api', '0005_alter_otpcode_options_business_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='business',
            name='business_type',
            field=models.CharField(choices=[('SHOP', 'Boutique / Vente'), ('TROC', 'Troc / Échange'), ('IMMO', 'Immobilier'), ('SERVICE', 'Services / Prestations')], default='SHOP', max_length=10),
        ),
    ]
