# Generated by Django 5.0 on 2026-02-24 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_api', '0007_migrate_existing_users'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Utilisateur', 'verbose_name_plural': 'Utilisateurs'},
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_whatsapp',
            field=models.CharField(max_length=20, unique=True, verbose_name='Numéro WhatsApp'),
        ),
    ]
