# Generated by Django 5.0 on 2026-02-26 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_api', '0008_alter_user_options_alter_user_phone_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpcode',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='otpcode',
            name='phone_number',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AddIndex(
            model_name='otpcode',
            index=models.Index(fields=['phone_number', '-updated_at'], name='base_api_ot_phone_n_c96849_idx'),
        ),
    ]
