# Generated by Django 5.0 on 2026-08-12 07:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='name')),
                ('slug', models.SlugField(help_text='Identifiant URL unique.', max_length=120, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/%Y/%m/', verbose_name='image')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive les sous-catégories aussi visuellement.', verbose_name='active')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text="Ordre d'affichage, du plus petit au plus grand.", verbose_name='sort order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('parent', models.ForeignKey(blank=True, help_text='Laisser vide pour une catégorie racine.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='catalog.category', verbose_name='parent category')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'db_table': 'catalog_categories',
                'ordering': ['sort_order', 'name'],
                'indexes': [models.Index(fields=['parent', 'is_active'], name='catalog_cat_parent__7449dd_idx'), models.Index(fields=['is_active', 'sort_order'], name='catalog_cat_is_acti_82390d_idx'), models.Index(fields=['slug', 'is_active'], name='catalog_cat_slug_358812_idx')],
            },
        ),
    ]
