# Generated by Django 5.0 on 2026-08-12 08:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='name')),
                ('brand', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='brand')),
                ('model', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='model')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('slug', models.SlugField(max_length=250, unique=True, verbose_name='slug')),
                ('specifications', models.JSONField(blank=True, default=dict, help_text='Caractéristiques génériques : écran, RAM, moteur, etc.', verbose_name='specifications')),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('ACTIVE', 'Actif'), ('ARCHIVED', 'Archivé')], db_index=True, default='DRAFT', max_length=20, verbose_name='status')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category', verbose_name='category')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'db_table': 'catalog_products',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['category', 'is_active'], name='catalog_pro_categor_0c41fb_idx'), models.Index(fields=['brand', 'is_active'], name='catalog_pro_brand_6d6e55_idx'), models.Index(fields=['status', 'is_active'], name='catalog_pro_status_157527_idx'), models.Index(fields=['slug', 'is_active'], name='catalog_pro_slug_5c4d14_idx')],
            },
        ),
    ]
