# Generated by Django 5.0 on 2026-08-12 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_productattribute_attributevalue_productvariant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variantattributevalue',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_values', to='catalog.productvariant', verbose_name='variant'),
        ),
    ]
