# Generated by Django 5.0 on 2026-08-12 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_variantattributevalue_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variantattributevalue',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_values', to='catalog.productvariant', verbose_name='variant'),
        ),
    ]
