# Generated by Django 5.0 on 2026-08-12 09:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_variantattributevalue_variant'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('media_type', models.CharField(choices=[('IMAGE', 'Image'), ('VIDEO', 'Vidéo')], default='IMAGE', max_length=10, verbose_name='media type')),
                ('url', models.URLField(max_length=1000, verbose_name='URL')),
                ('thumbnail_url', models.URLField(blank=True, max_length=1000, verbose_name='thumbnail URL')),
                ('alt_text', models.CharField(blank=True, help_text="Description pour l'accessibilité et le SEO.", max_length=255, verbose_name='alt text')),
                ('is_primary', models.BooleanField(default=False, help_text='Image principale affichée en premier.', verbose_name='primary')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='sort order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='catalog.product', verbose_name='product')),
                ('variant', models.ForeignKey(blank=True, help_text='Laissez vide pour un média global au produit.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media', to='catalog.productvariant', verbose_name='variant')),
            ],
            options={
                'verbose_name': 'product media',
                'verbose_name_plural': 'product media',
                'db_table': 'catalog_product_media',
                'ordering': ['sort_order', 'created_at'],
                'indexes': [models.Index(fields=['product', 'sort_order'], name='catalog_pro_product_2228f4_idx'), models.Index(fields=['variant', 'sort_order'], name='catalog_pro_variant_adf5df_idx'), models.Index(fields=['media_type', 'is_primary'], name='catalog_pro_media_t_30f680_idx')],
            },
        ),
    ]
