# Generated by Django 5.0 on 2026-08-18 10:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='last_accessed_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date de dernière activité sur le panier', verbose_name='dernier accès'),
        ),
    ]
