# Generated by Django 5.0 on 2026-08-20 14:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('marketplace', '0003_offer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('CONFIRMED', 'Confirmée'), ('PROCESSING', 'En préparation'), ('SHIPPED', 'Expédiée'), ('DELIVERED', 'Livrée'), ('CANCELLED', 'Annulée')], db_index=True, default='PENDING', max_length=20, verbose_name='statut')),
                ('currency', models.CharField(max_length=3, verbose_name='devise')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='sous-total')),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='frais de livraison')),
                ('total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='total')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mis à jour le')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='acheteur')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='accounts.sellerprofile', verbose_name='vendeur')),
            ],
            options={
                'verbose_name': 'commande',
                'verbose_name_plural': 'commandes',
                'db_table': 'orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='nom du produit')),
                ('variant_name', models.CharField(blank=True, max_length=255, verbose_name='nom de la variante')),
                ('sku', models.CharField(blank=True, max_length=100, verbose_name='SKU')),
                ('quantity', models.PositiveIntegerField(verbose_name='quantité')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='prix unitaire')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='sous-total')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='marketplace.listing', verbose_name='annonce')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='commande')),
            ],
            options={
                'verbose_name': 'article de commande',
                'verbose_name_plural': 'articles de commande',
                'db_table': 'order_items',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['buyer', 'status'], name='order_buyer_status_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['seller', 'status'], name='order_seller_status_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_at'], name='order_created_at_idx'),
        ),
    ]
