# Generated by Django 5.0 on 2026-08-26 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='seller',
            field=models.ForeignKey(default='1ee39b2a-6dcf-4ff9-9f5c-aea219c24616', on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='accounts.sellerprofile', verbose_name='vendeur'),
            preserve_default=False,
        ),
    ]
