# Generated by Django 5.0 on 2026-08-26 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderitem_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('PROCESSING', 'En préparation'), ('SHIPPED', 'Expédié'), ('DELIVERED', 'Livré'), ('CANCELLED', 'Annulé')], db_index=True, default='PENDING', max_length=20, verbose_name='statut'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='mis à jour le'),
        ),
    ]
